/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

import bcrypt from "bcrypt";

export async function seed(knex) {
  await knex("users").del();

  const now = knex.fn.now();

  await knex("users").insert([
    {
      id: 1,
      first_name: "Ritesh",
      last_name: "Kumar",
      profile_name: "ritesh_k",
      email: "ritesh@example.com",
      selfie: "assets/user/download(1).jpeg",
      best_pic: "assets/user/download.jpeg",
      mobile_number: "9876543210",
      password: bcrypt.hashSync("Password@1", 10),
      gender: "male",
      language: "en",
      dob: "1998-06-15",
      height: 172,
      weight: 68,
      body_type: "athletic",
      hair_color: "black",
      eye_color: "brown",
      nationality: "Indian",
      region: "Uttar Pradesh",
      city: "Lucknow",
      sexual_orientation: "straight",
      education: "B.Tech",
      field_of_work: "Software Development",
      relationship_status: "single",
      zodiac_sign: "gemini",
      smoking: "no",
      drinking: "occasionally",
      tattoos: false,
      piercings: false,
      about_me: "Software developer and tech enthusiast.",
      about_perfect_match: "Looking for someone supportive and kind.",
      interested_in: "favorite_music",
      favorite_music: "Pop, Jazz",
      source: "google",
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 2,
      first_name: "Aisha",
      last_name: "Khan",
      profile_name: "aisha_k",
      email: "aisha@example.com",
      selfie: "assets/user/virat.jpg",
      best_pic: "assets/user/user1-128x128.jpg",
      mobile_number: "9123456780",
      password: bcrypt.hashSync("Password@2", 10),
      gender: "female",
      language: "en",
      dob: "1997-03-22",
      height: 160,
      weight: 55,
      body_type: "slim",
      hair_color: "brown",
      eye_color: "black",
      nationality: "Indian",
      region: "Delhi",
      city: "New Delhi",
      sexual_orientation: "straight",
      education: "MBA",
      field_of_work: "Marketing",
      relationship_status: "single",
      zodiac_sign: "aries",
      smoking: "no",
      drinking: "no",
      tattoos: false,
      piercings: true,
      about_me: "Creative, traveler, and photographer.",
      about_perfect_match: "Honest and adventurous partner.",
      interested_in: "favorite_movie",
      favorite_movie: "La La Land",
      source: "instagram",
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: 3,
      first_name: "Omar",
      last_name: "Ali",
      profile_name: "omar_a",
      email: "omar@example.com",
      selfie: "assets/user/virat.jpg",
      best_pic: "assets/user/download.jpeg",
      mobile_number: "9012345678",
      password: bcrypt.hashSync("Password@3", 10),
      gender: "male",
      language: "en",
      dob: "1995-11-10",
      height: 178,
      weight: 75,
      body_type: "average",
      hair_color: "black",
      eye_color: "brown",
      nationality: "Indian",
      region: "Maharashtra",
      city: "Mumbai",
      sexual_orientation: "straight",
      education: "B.Com",
      field_of_work: "Business",
      relationship_status: "single",
      zodiac_sign: "scorpio",
      smoking: "occasionally",
      drinking: "yes",
      tattoos: true,
      piercings: false,
      about_me: "Business-minded and fitness lover.",
      about_perfect_match: "Someone ambitious and caring.",
      interested_in: "favorite_sport",
      favorite_sport: "Cricket",
      source: "facebook",
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ]);
}
